### ISSUE TITLE
[week2] 수요일 PR 

### ISSUE THREAD

**Issue by Jinsujin** [dukcode/sidedish#137]
# 🙋🏻‍♀️ 롤로님께 🙋🏻
 
# 💡 Issue
1. dukcode/sidedish#101
2. dukcode/sidedish#119
3. dukcode/sidedish#135

# 📝 Tasks

## 1. 두번째 PR 리뷰 반영
- [x] setProperties 주석제거, 함수 이름 수정
- [x] HomeView: CollectionVIew 리펙토링
- [x] Product Model 에서 사용하는 commnet 를 enum 에서 가져오도록 수정
- [x] ProductRepository와 ProductDetailRepository가 다루는 Error 타입 분리
- [x] RootNavigationController 제거
- [x] DishCollectionWrapper 의 역할 분명히 하기

### 🔹 고민과 해결
- DIContainer 의 역할에 대한 고민

### 🔹 작업
- 이미지들이 모두 오는 작업을 디스패치 그룹으로 묶어 한번에 리턴하게 만들기
-  비동기로 요청하였기에 무작위 순서로 오는 이미지들을 순서에 맞춰 정렬시키기
- 비동기로 가져온 데이터를 컬렉션뷰에 보여주는 로직
### 🔹 고민과 해결
- 하나의 카테고리에 속한 여러장의 이미지가 다운로드 모두 되었을때 한번에 보여줍니다.
- 모든 이미지를 다운받는데 걸리는시간이 8초가 걸립니다(카페 와이파이에서)
- 집 와이파이에서는 1초가 걸립니다
- 캐싱을 생각해 봤지만, 처음부터 이미지 받는 시간이 느리기 때문에 의미가 없다고 생각합니다.
- 혹시 좋은 방법이 없을까요...?

### 🔹 실행 화면
<img width="321" alt="상품 이미지 화면에 보여주기" src="https://user-images.githubusercontent.com/12508578/165455725-e17eeb21-5620-4bd3-ae9b-15e56ee081cf.png">
