### ISSUE TITLE
서버 API 와 연결하여 데이터를 홈화면에 보여준다

### ISSUE THREAD

**Issue by Jinsujin** [dukcode/sidedish#140]
# Tasks
- [x] API Repository 작성
- [x] 서버에서 가져오는 데이터를 앱내에서 사용하는 데이터로 변환
- [x] 가져온 데이터를 화면에 보여준다
