### ISSUE TITLE
[week2] 수요일 PR 리뷰 반영

### ISSUE THREAD

**Issue by Jinsujin** [dukcode/sidedish#143]
### Tasks
- [x] cell identifier 를 모든 셀에서 사용할수 있도록 extension 으로 작성하기
- [x] image 를 서버에서 가져올때, 값이 없으면 빈 Data() 가 아닌 nil 을 넣도록 변경
- [x] Factory 로직 수정: 변경된 Category struct 에 맞게 수정
- [x] `dishes[product.category]` 가독성 수정
