### ISSUE TITLE
[week2] 마지막 PR 날리기

### ISSUE THREAD

**Issue by Jinsujin** [dukcode/sidedish#146]
# 🙋🏻‍♀️ 롤로님께 🙋🏻
안녕하세요 롤로! 어느덧 마지막 PR 이네요 😭 
네트워크를 붙이는 작업을 하며 구조를 어떻게 잡아야 할 지 고민이 많았습니다.
어느정도 윤곽이 잡히기 시작해 이제 리스트 데이터를 화면에 연결하는 작업에 들어갔습니다.
하지만 아직 정리해야 할 부분이 많아 보여 아쉬움이 많이 남아요. 마지막까지 잘 부탁 드립니다!

# 💡 Issue
1. dukcode/sidedish#143

# 📝 Tasks

## 1. PR 리뷰 반영
- [x] cell identifier 를 모든 셀에서 사용할수 있도록 extension 으로 작성하기
- [x] image 를 서버에서 가져올때, 값이 없으면 빈 Data() 가 아닌 nil 을 넣도록 변경
- [x] Factory 로직 수정: 변경된 Category struct 에 맞게 수정
- [x] `dishes[product.category]` 가독성 수정

### 🔹 작업
앱의 비지니스 로직에서 사용하는 모델과 API 에서 받아오는 데이터 모델을 분리했습니다.
서버에서 가져온 모델이 이미 구현된 앱 로직에 영향을 덜 미치게끔 하기 위함입니다.
### 🔹 고민과 해결
홈화면에서 상품 리스트를 보여주기 위해서는 다음과 같은 흐름을 거칩니다:
1. category list API 호출: 전체 카테고리에 대한 데이터를 받아온다
2. category list 를 모두 순회하며 category.id 를 키값으로 그에 해당하는 product list API 호출
화면하나를 보여주기 위해 두가지 API 를 사용해야 합니다. 카테고리의 갯수-N 번 만큼 product list API 를 호출해야 합니다. 
```swift
requestCategoryListAPI { result in 
...
   for 카테고리 in 받아온카테고리리스트 {
     requestProductListAPI(카테고리.id) { result in
        // 이제서야 해당 카테고리에 어떤 제품이 있는지 알 수 있게 된다
     }
   }
}
```
위의 코드처럼 completion 안에 completion 이 호출되는 형태가 됩니다.
좀 더 좋은 방법이 없을지 함께 고민중 입니다

### 🔹 작업
Repository 에서 데이터를 가져올때 Service 를 통해 가져오게 됩니다.
서버에 요청을 보내 DTO 객체로 파싱한 후 completion 으로 결과를 전해줍니다.

### 🔹 고민과 해결
객체를 
1. 앱 내부 비지니스 로직에서 사용하는 Entity
2. 서버를 통해 가져오는 데이터를 디코딩한 DTO 
두개로 나누게 되면서, DTO -> Entity 로의 변환을 어디서 담당해야 할지 고민이 생겼습니다.
- Rosa 가 생각한 방법은 각 struct 구조체 내부에서 DTO(self) -> Entity 로 변환하는 방법: 
  - Repository 레이어에서 담당한다
- Ebony 가 생각한 방법은 DTO형태 그대로 앱 내부에서 활용하기 ( entity와 dto를 구분하지 않고 사용 )
