### ISSUE TITLE
[week1] 첫번째 PR 리뷰 반영

### ISSUE THREAD

**Issue by Jinsujin** [dukcode/sidedish#78]
### Task
- MockFactory 수정
    - [ ]  가짜 데이터를 생성하는 struct 의 네이밍을 명확하게 변경했습니다
    - [ ]  인스턴스 생성할때 데이터를 몇개 생성할지 인자로 받도록 했습니다.
- [ ]  할인율을 associated value 을 가진 enum 으로 수정했습니다.
- [ ]  final 키워드를 붙여 성능향상을 했습니다
- [ ]  Repository protocol 분리
    - 전체 화면에서 사용하는 Repository 와 상세 화면에서 사용하는 DetailRepository 로 분리했습니다.
- [ ]  DIContainer 에서 만드는 ViewController 의 타입을 enum 으로 받아서 생성하도록 변경
